### ISSUE TITLE
Save custom color gradient

### ISSUE THREAD

**Issue by cmkewish** [jkotan/lavue#137]
We have been using LaVue for EIGER2 data at the Australian synchrotron, since the new Dectris API broke the live-view functionality of ALBULA due to a change in the monitor interface: we use a gradient to mimic ALBULA's default high-contrast scale which we were used to for EIGER, plus a blue clipping indicator: {0.0: white, 0.15: black, 0.4: red, 0.7: yellow, 0.99: white, 1.0: blue}

![Screenshot from 2019-04-25 07-27-46](https://user-images.githubusercontent.com/10864087/56695193-cc477300-672b-11e9-86c2-166aa0d61042.png)

It's great that you can define a custom color gradient in the widget, it would also be nice to be able to save one or more user-defined gradients, or alternatively specify a custom gradient from a command line JSON.

**Comment by jkotan** [comment]
Hi @cmkewish, 

yes, indeed it would be helpful.
I've just added PR #138 which:
1) adds `highcontrastclip` color gradient you defined above
2) in the expert mode (lavue -m expert) you can `Save/Remove` costom gradient by clicking the right mouse button on the color gradient histogram bar
3) the gradients are stored in '~/.config/DESY/LaVue.conf' so you can edit them from the script e.g.
```
[CustomColorGradients]
superblue="{'ticks': [(0.0, (0, 0, 0, 255)), (0.42280701754385963, (0, 168, 157, 255)), (1.0, (255, 255, 255, 255))], 'mode': 'rgb'}"
superpink="{'ticks': [(0.0, (0, 0, 0, 255)), (0.42280701754385963, (168, 3, 165, 255)), (1.0, (255, 255, 255, 255))], 'mode': 'rgb'}"
```
4) the stored gradients ar loaded back  on new start `lavue`

I hope it should work for you ;)

**Comment by jkotan** [comment]
I've add the PR to v2.7.0

**Comment by cmkewish** [comment]
This is great, and amazingly fast response time also! 
I will update our installation and test this today.
Thanks Jan 👍

**Comment by cmkewish** [comment]
Yes, this worked perfectly. Thanks.
