### ISSUE TITLE
config file name of none default instances

### ISSUE THREAD

**Issue by jangarrevoet** [jkotan/lavue#538]
Hi Jan,
currently the config file names of none default is something like "Lavue: other_instance.conf". Would it be possible to remove the space since it is rather anoying to work with spaces in names on linux. (I am not sure about the colon either. I thend to avoid it whenever possible.)
thanks,
Jan

**Comment by jkotan** [comment]
Sound resonable. I will do it. But of course then I have to support both configuration file for backward compatibility

**Comment by jkotan** [comment]
Hi Jan, 
I've just created PR #541. Does it look reasonable for you?

**Comment by jangarrevoet** [comment]
Hi Jan,
I am fine with that.
thanks,
Jan

**Comment by jangarrevoet** [comment]
Only thing one might do is add a deprecation warning to the older style so that it can be phased out at some point.
