### ISSUE TITLE
invert x/y-axes of window widgets in projections mode

### ISSUE THREAD

**Issue by lrlunin** [jkotan/lavue#681]
Hello, first of all I would like to thank you for creating and maintaining such software which helps us everyday.

We noticed that x/y-axes of side projections widgets will not be inverted if x/y-axes of main 2D plot were inverted. This may give the impression that the projection is not working properly.
![image](https://user-images.githubusercontent.com/1849145/204103999-fbf6ee29-15b8-4e99-9c70-35b050b25b4b.png)
![image](https://user-images.githubusercontent.com/1849145/204103958-9ed35d82-c871-46f3-8a2c-e8a1017c3245.png)

My proposal: on change of axes inversion of the main 2d plot apply the same orientation of axes to side widgets. In the same time inversion of side widgets' should not change orientation of the main 2d plot. In this case user will always have correct projections and still has an opportunity to set up in other way if it is required.

**Comment by jkotan** [comment]
Thanks for the ticket. I will look at it.

**Comment by jkotan** [comment]
It looks like the transformations widget (with `keep current coordinates`) provides the same functionality so it is not enough to synchronize invert actions with other plots but also with transformations widgets. 
Things getting even more complicated  when  `keep current coordinates` is off i.e. what to do?

Until I found the proper solution to do not give the impression that the projection is not working properly I will hide the corresponding invert actions.

**Comment by jkotan** [comment]
Since It is possible to invert-x/y axes by transpose action I think there is  not need to support these additional action.  So I close the ticket.  Please re-open the ticket if it is needed.
