### ISSUE TITLE
Unable to connect to ZMQ stream when data source contains "/"

### ISSUE THREAD

**Issue by jangarrevoet** [jkotan/lavue#710]
Hi,
I am getting the following error when I try to select a data source that contains a "/".
As extra info, the data source is "/detectors/something/something", hence the "detectors" in the traceback.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lavuelib/imageSource.py", line 1799, in connect
    hwm = int(shost[2]) if (len(shost) > 2 and shost[2]) else 2
ValueError: invalid literal for int() with base 10: 'detectors'
```

**Comment by jangarrevoet** [comment]
It can be fixed by changing the following:
```shost = str(self._configuration).split("/")```
to
```shost = str(self._configuration).split("/", maxsplit=1)```

Shall I open a PR or will you @jkotan ?

**Comment by jkotan** [comment]
Thanks Jan for the ticket. If you have a working branch please open PR. Otherwise I will do it.

**Comment by jkotan** [comment]
@jangarrevoet ,  I thing if we merge your patch the HWM will be set wrongly. Do you really need to use "/" in datasources?

**Comment by jangarrevoet** [comment]
From the construct in the connect method it looks like the hwm is not always passed as part of the configuration. Any way to always add it to the configuration? Then one can or do:
```hwm=int(str(self._configuration).rsplit("/", maxsplit=1)[1])```
or one could instead of using "/" as a separator between parameters switch to ":"?

The reason why I use "/" is since the datasets have a hierarchy, hence "/" is a logical choice and is easily understandable by users.

**Comment by jkotan** [comment]
I have to think about it more because your both propositions are not fully backward  compatible.

**Comment by jangarrevoet** [comment]
It will indeed, but how many people are actually setting the HWM? It will only break for them. In any case the break in API is small.

**Comment by jkotan** [comment]
@jangarrevoet, I've just added to your PR an option to set colon separation for ZMQ configuration
