### ISSUE TITLE
display names for ROIs instead of numbers if assigned

### ISSUE THREAD

**Issue by lrlunin** [jkotan/lavue#723]
Hello @jkotan,

I really appreciate this amount of work you invested in this package which we daily use in our lab. I would be happy to request some features I found useful for us. I also would be happy to implement them and create a pull request. Most of them involve change of the GUI. So I installed Qt Design Studio to try to modify the GUI but I cannot find the project file. Could you add it into the repository?

The first feature is rather simple and described in the title of the issue. When you have >10 ROIs it is really hard to fast determine which of the ROIs correspond to one or other name.

**Comment by jkotan** [comment]
Hello @lrlunin,

your PR's are welcome. I don't use  Qt Design Studio but only qt designer.

**Comment by lrlunin** [comment]
Thanks, it works. Can I only open the files separately or there is some kind of "master" file which represents the whole program window?

**Comment by jkotan** [comment]
I edit them separately.

**Comment by jkotan** [comment]
@lrlunin , thanks to the ticket. The new feature is added to v2.90.0. To enable it one need to check  "Label ROIs with aliases"  in the lavue configuration.

**Comment by lrlunin** [comment]
> @lrlunin , thanks to the ticket. The new feature is added to v2.90.0. To enable it one need to check "Label ROIs with aliases" in the lavue configuration.

Thank you for such a great software! An ultimative software to obtain and check the images 🥰
