### ISSUE TITLE
zmq auto data sources not shown when switching to multiple image sources

### ISSUE THREAD

**Issue by jangarrevoet** [jkotan/lavue#725]
When the bug is triggered the only data source that can be selected is "ALL". How to reproduce:

1. Have any number of image sources.
2. You can connect to zmq streams and select the data source you want (not needed to reproduce the bug, just to show it works)
3. Change the number of data sources
4. You will now only have "ALL" available in the data source drop down list

**Comment by jkotan** [comment]
@jangarrevoet , Could you please check if #727 fixes the issue
