### ISSUE TITLE
configuration-path option doesn't work

### ISSUE THREAD

**Issue by yuelongyu** [jkotan/lavue#777]
When starting lavue with configuration-path option, the configuration in the file is not loaded.
```
lavue -m expert --configuration-path /tmp/LaVue.conf
```

**Comment by yuelongyu** [comment]
I figured out how it works, looks like it searches conf file from ```configuration-path/organization/LaVue.conf```.  So if the organization name is default, it's important to copy the whole DESY folder instead of the LaVue.conf itself.

**Comment by jkotan** [comment]
Hi @yuelongyu, Yes, lavue stores configuration in QT standard way i.e. QtSettings, where location of the configuration is stored below:  ` <base configuration path> / <organization or domain> / <program name [: instance] >`.conf . Maybe we should change configuration path to base configuration path, what do you think?

**Comment by yuelongyu** [comment]
hi @jkotan , I think an error message should be enough. When starting lavue with configuration-path, if there is no config file, it shows an error message.

**Comment by jkotan** [comment]
@yuelongyu , but configuration file may not exist when you what to create a new configuration file from the scratch
